# Generated by Django 3.1.6 on 2021-05-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourproduct', '0003_aboutus_career'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='Career',
        ),
    ]
